update st-urlhandler script

diff --git a/st-urlhandler b/st-urlhandler
--- a/st-urlhandler
+++ b/st-urlhandler
@@ -18,8 +18,8 @@ urls="$(
 
 [ -z "$urls" ] && exit 1
 
-while [ $# != 0 ]; do
-	case "$1" in
+for arg in "$@"; do
+	case "$arg" in
 		-c)
 			echo "$urls" | dmenu -i -p "copy url:" -l 10 | tr -d "\n" | xclip -sel clip
 			;;
@@ -29,9 +29,8 @@ while [ $# != 0 ]; do
 			setsid xdg-open "$sel" >/dev/null 2>&1 &
 			;;
 		*)
-			printf "invalid option: -%s\n" "$1"
+			echo "invalid option: $arg" >&2
 			exit 1
 			;;
 	esac
-	shift
 done
